name: Save run number

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a tag with the run number
        run: |
          git tag run-${{ github.run_number }}
          git push origin run-${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GA_PAT }}
