name: Use run number in second workflow

on:
  workflow_dispatch:

jobs:
  deploy: # doesn't make sense but whatever
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Get latest tag
        run: |
          git tag --list

      - name: Use run number in shell script
        shell: pwsh
        run: |
          echo "https://whatever/3_23_1-$env:RUN_NUMBER/ShopFlex-$env:RUN_NUMBER.war"
