name: Use run number in second workflow

on:
  workflow_dispatch:

jobs:
  deploy: # doesn't make sense but whatever
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download run number artifact
        uses: actions/download-artifact@v2
        with:
          name: run-number
          path: ./

      - name: Use run number in shell script
        shell: pwsh
        run: |
          $runNumber = Get-Content -Path .\run_number.txt

          echo "https://whatever/3_23_1-$runNumber/ShopFlex-$runNumber.war"
